server:
  port: 8080

spring:
  application:
    name: Recipease
 
  datasource:
    dirverClassName: org.postgresql.Driver
    initilization-mode: never
    password: recipease
    username: postgres
    url: jdbc:postgresql://34.70.51.191:5432/recipease
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: recipease
    show-sql: false
